name: crayon
channels:
  - pytorch
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - attrs
  - backcall
  - blas
  - bleach
  - ca-certificates
  - certifi
  - cycler
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - fontconfig
  - freetype
  - glib
  - gmp
  - gst-plugins-base
  - gstreamer
  - icu
  - importlib_metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - kiwisolver
  - ld_impl_linux-64
  - libedit
  - libffi
  - libpng
  - libsodium
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - nbconvert
  - nbformat
  - ncurses
  - ninja
  - nltk
  - notebook
  - numpy
  - numpy-base
  - olefile
  - openssl
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - ptyprocess
  - pygments
  - pyparsing
  - pyqt
  - pyrsistent
  - python
  - python-dateutil
  - pytorch
  - pytz
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - readline
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - sqlite
  - statsmodels
  - terminado
  - testpath
  - tk
  - torchvision
  - tornado
  - traitlets
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - boto3
    - botocore
    - cffi
    - chardet
    - click
    - docutils
    - filelock
    - idna
    - jmespath
    - mecab-python3
    - packaging
    - portalocker
    - pycparser
    - regex
    - requests
    - s3transfer
    - sacrebleu
    - sacremoses
    - sentencepiece
    - tokenizers
    - tqdm
    - transformers
    - typing
    - urllib3